sudo: required
dist: trusty

language: c

compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "deb http://downloads.skewed.de/apt/trusty trusty universe"
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - pkg-config
      - flex
      - bison
      - libpcre3 
      - libpcre3-dev
      - splint
      - indent
      - python3
      - python3-dev
      - libpython3.4 
      - libpython3.5 
      - python3-pip
      - python-graph-tool

before_install:
 - python3 -m pip install pylint --user

script: make
