dist: trusty
sudo: false
language: c
cache:
  directories:
  - "~/.stack/"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- rvm use 2.1 --install --binary --fuzzy
install:
- travis_wait 30 stack --install-ghc --copy-bins install language-python
- travis_wait 30 stack --install-ghc --copy-bins build
- stack install hlint
- gem install danger danger-hlint
script:
- stack test --only-dependencies
- "./bin/hlint '--ignore=Parse error' src"
- "./bin/hlint '--ignore=Parse error' app"
- PATH=./bin:$PATH danger
deploy:
  provider: releases
  api_key:
    secure: XcnEfQ5VBYFRrfj3ekIWXzoxFIbeSkV/+/1viioCsdhzN9E5D4zZKQEAwVui8BNo4zqyHR6bHDVLv/g0UI6/z+vsAgvxFc3JsajNUBB6KX2seEa6Rm25q9fq1lUbDqmDuRp29E/9S0iUv7IXs03KpotPS4i48VWXzP1yhmiIXXSQH0cV+BH7EyVIz9RSqEvQoMgbEWP8RiN9sJoRv8EV5wVfC9wE86s+19fPkkF45tQOvhFaeW8AxDtCWIixcdy+1gKX1jVyBBsQ8KgW8QVdoMxdEcL+UU6/HeSG49yi64hi5RMlpRd+ue6jFLHpg+atZtD1FQSe9Iu4XAuuApvdmRq3vuIKt3/5/lE9o96mCZdonAfoKc+Bz69zYXbkbSNBLUnJzhjrDn6BZyMxbjoU6m4IceLfXwPV/Ao5CxRBeEop+FzZe+gDwDNrOd/EG9Lvx8sY60wkdCiQje/BGJzotW9C2fEixHar09Eb0/5mTYVGk/NlzOpc2yMhiwz2f3uQXZDijuQ7NKWqQq81KKUxU0AUHsNOHU60MOtXJify9psMcjj1KLURsAj2iRTdiX3gm9idEqKB3Rs9crUAwqmQOTBGIibbP3dLbR3b0YwGxSC0WaBUZMyHacKKN7S16YET5JH9xyQS2SnxsOleZ0SwIASCj9XmrhOCQ1jRRPusefw=
  file:
  - bin/count
  - bin/plagiarism
  - bin/diagnostics
  skip_cleanup: true
  on:
    tags: true
    repo: Submitty/AnalysisTools
