dist: trusty
sudo: false
language: c
cache:
  directories:
  - "~/.stack/"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- rvm use 2.1 --install --binary --fuzzy
install:
- travis_wait 30 stack --install-ghc --copy-bins install language-python
- travis_wait 30 stack --install-ghc --copy-bins build
- stack install hlint
- gem install danger danger-hlint
script:
- stack test --only-dependencies
- "./bin/hlint '--ignore=Parse error' src"
- "./bin/hlint '--ignore=Parse error' app"
- PATH=./bin:$PATH danger

deploy:
  provider: releases
  api_key:
    secure: jFoXeyPLYm1ZrtFpTa2TCQkNFfNzv/yxxXYn7aSyOpocKbEXNJhjD8gZZcREr4cHQMzYq3AWJBIZFP32/OZb5wO1fDoQ9URZvH3yKmWvWH7mXhhqivfHG2iG7/USsHfDNZoXpo+YLZLWDPyo4VBHpkiCbNkMr8I8XR84ErgoteNxkuOJ0m+Z7Yu9uVXsOYqNEaNpj0e0gCsk3Tzx5WUNcIeJY48XGgV/xU1qucM5bU4sy0Zk/6XLTZ9F/em384d6RaHU3TCdVUQ36yn8WCb8t6xj/LvJCMjV/rlC+HXT+NbONGoLLPN+5R4/S3zY7lIvl8rcTHRMvZYk2fkygC5+lJ/9bKSZv7iuq3+VoNeRSaRD5oojIg5C9gZSPdMYhnRjfJDm6y64RG2kazcw5/UoCiYTxVe4yUhhgjm3DTZdPHAyvBeu8tusqbleowfgibTjcbm5fGuNGVIJkz1CrzFg7s/M+W2A2caeH3Dc/7OekMeafWAkswjtf6b/9/ocpfuMV5kDJ96i1WMYLnMw/pRDzi6sMAt3WhF/18mwBujDIUJQ1VBBL4/WRbT0mTzv4XfBU6ZV1DdvriukVvsnacVUaDyyjxz3xVTnvKMNZh1HfEk0MEA+e2O+bO4uyiMmq2L4svwFL02OpoOfhcSDAnA8M+DXavm2r7mmzdN1m0r9TXg=
  file:
  - bin/count
  - bin/plagiarism
  - bin/diagnostics
  skip_cleanup: true
  on:
    tags: true
    repo: Submitty/AnalysisTools
