#!/bin/bash

if [ $# -le 1 ]; then
    echo "Usage: $0 <directory> [-o <path>] [-h]"
    exit 1
fi

TIMESTAMP=$(./bin/walk $@)
shift

OUTPUT_MOD="cat"

while getopts ":o:h" opt; do
    case $opt in
        o)
            OUTPUTFILE=$OPTARG
            ;;
        h)
            OUTPUT_MOD="./bin/make_table"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ -z "$OUTPUTFILE" ]; then
    ./bin/genpairs $TIMESTAMP | ./bin/compare_fingerprints $TIMESTAMP | sort -nr | $OUTPUT_MOD | less -S;
else
    ./bin/genpairs $TIMESTAMP | ./bin/compare_fingerprints $TIMESTAMP | sort -nr | $OUTPUT_MOD > $OUTPUTFILE;
fi
