from PIL import Image
import check2_helper as help
resize = (512//2,512//2)
im = Image.new('RGB', (512,512), 'white')
im2 = Image.open("ca.jpg")
im3 = Image.open("tr.jpg")
im4 = Image.open("im.jpg")
im5 = Image.open("hk.jpg")
im2v2 = help.make_square(im2)
im3v2 = help.make_square(im3)
im4v2 = help.make_square(im4)
im5v2 = help.make_square(im5)
im.paste(im2v2.resize(resize), (0,0))
im.paste(im3v2.resize(resize), resize)
im.paste(im4v2.resize(resize), (resize[0],0))
im.paste(im5v2.resize(resize), (0,resize[1]))
im.show()